name = "Hardcore Vanilla+"
author = "cherring0011-eng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15b0bcc00e997bd0af6566c1ee4475496beba1173aa7566805008aa7bfd3c9d6"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
