name = "Hardcore Vanilla+"
author = "cherring0011-eng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "356cc15188e0b45336af92f7ebcadfb710db57a3c23376c14c228afd805a8762"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
